name="id:name"
email="id:email"
phone="id:phone"
textarea="id:textarea"
gender="id:male"
days_checkbox="xpath://label[text()='Days:']//following-sibling::div//input"
country="id:country"
colors="id:colors"
animalslist="id:animals"
datepicker1="id:datepicker"
datepicker2="id:txtDate"
startdate="id:start-date"
enddate="id:end-date"
submit_btn="xpath://button[@class='submit-btn']"
file1_data="id:singleFileInput"
upload_fiele="xpath://button[text()='Upload Single File']"
success_msg1="id:singleFileStatus"
file2_data="id:multipleFilesInput"
upload_file2="xpath://button[text()='Upload Multiple Files']"
success_msg2="id:multipleFilesStatus"
table="xpath://table[@name='BookTable']//tr//td"
dynamic_table="xpath://table[@id='taskTable']//tbody//tr/td"
starttostop="xpath://button[starts-with(text(),'ST')]"
alert1="id:alertBtn"
alert2="id:confirmBtn"
alert3="id:promptBtn"
alert_msg="id:demo"
newtab="xpath://button[text()='New Tab']"
newbrowser="id:PopUp"
mouseover="xpath://div[@class='dropdown']"
doubleclick="xpath://button[text()='Copy Text']"
drag="id:draggable"
drop="id:droppable"
slide="id:slider-range"
dropdownbox="id:dropdown"
svg="xpath://*[name()='svg']/*[name()='circle']"
rects="xpath://*[name()='svg']/*[name()='rect']"
ovals="xpath://*[name()='svg']/*[name()='polygon']"
svg_attribute_values="fill"
dropdown="id:comboBox"
dropdown_list1="xpath://div[@id='dropdown']//div"
links_text="xpath://div[@id='mobiles']//label"
links_text_a="xpath://div[@id='laptops']//a"
broken_link="xpath://div[@id='broken-links']//a"

p1="id:para1"
sec1="id:input1"
sec1_btn="id:btn1"
p2="id:para2"
sec2="id:input2"
sec2_btn="id:btn2"
p3="id:para3"
sec3="id:input3"
sec3_btn="id:btn3"
footer_links="xpath://*[@id='PageList1']/div/ul/li//a"
shadow="xpath://*[@id='shadow_host']"

