name="id:name"
email="id:email"
phone="id:phone"
textarea="id:textarea"
gender="xpath://*[@id='male']"
days_checkbox="xpath://label[text()='Days:']//following-sibling::div//input"
country="id:country"
colors="id:colors"
animalslist="id:animals"
datepicker1="id:datepicker"
datepicker2="id:txtDate"
startdate="id:start-date"
enddate="id:end-date"
submit_btn="xpath://button[@class='submit-btn']"
file1_data="id:singleFileInput"
upload_fiele="xpath://button[text()='Upload Single File']"
success_msg1="id:singleFileStatus"
file2_data="id:multipleFilesInput"
upload_file2="xpath://button[text()='Upload Multiple Files']"
success_msg2="id:multipleFilesStatus"
table="xpath://table[@name='BookTable']//tr//td"
dynamic_table="xpath://table[@id='taskTable']//tbody//tr/td"
starttostop="xpath://button[starts-with(text(),'ST')]"
alert1="id:alertBtn"
alert2="id:confirmBtn"
alert3="id:promptBtn"
alert_msg="id:demo"
newtab="xpath://button[text()='New Tab']"
newbrowser="id:PopUp"
mouseover="xpath://div[@class='dropdown']"
doubleclick="xpath://button[text()='Copy Text']"
drag="id:draggable"
drop="id:droppable"
slide="id:slider-range"
dropdownbox="id:dropdown"



